# Generated by Django 5.0.6 on 2024-06-11 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(unique=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Collin Sinclair Cell' or 'PPA Main'",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Responsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Responsibilities",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "responsibilities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Choose any and only responsibilities that are inseparable from this role.",
                        to="core.responsibility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if User is selected above.",
                        max_length=32,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if User is selected above.",
                        max_length=32,
                    ),
                ),
                (
                    "other_email_addresses",
                    models.ManyToManyField(
                        blank=True, related_name="person_other_emails", to="core.email"
                    ),
                ),
                (
                    "other_phone_numbers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="person_other_phones",
                        to="core.phonenumber",
                    ),
                ),
                (
                    "primary_email_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_primary_email",
                        to="core.email",
                    ),
                ),
                (
                    "primary_phone_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_primary_phone",
                        to="core.phonenumber",
                    ),
                ),
                (
                    "responsibilities",
                    models.ManyToManyField(blank=True, to="core.responsibility"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="core.role")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "start_date",
                    models.DateField(
                        help_text="The date of the first rehearsal, usually."
                    ),
                ),
                (
                    "opening_date",
                    models.DateField(
                        help_text="The date of the first performance, usually."
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True,
                        help_text="The date of the last performance, usually.",
                        null=True,
                    ),
                ),
                ("locations", models.ManyToManyField(blank=True, to="core.location")),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productiontype",
                    ),
                ),
                ("staff", models.ManyToManyField(blank=True, to="core.staffmember")),
            ],
        ),
    ]
