# Generated by Django 5.0.6 on 2024-06-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staffmember",
            ),
        ),
    ]
