# Generated by Django 5.0.6 on 2024-06-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_staffmember_reports_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committee",
            options={"verbose_name": "Committee", "verbose_name_plural": "Committees"},
        ),
        migrations.AlterModelOptions(
            name="email",
            options={"verbose_name": "Email", "verbose_name_plural": "Emails"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="phonenumber",
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
            },
        ),
        migrations.AlterModelOptions(
            name="production",
            options={
                "verbose_name": "Production",
                "verbose_name_plural": "Productions",
            },
        ),
        migrations.AlterModelOptions(
            name="productiontype",
            options={
                "verbose_name": "Production Type",
                "verbose_name_plural": "Production Types",
            },
        ),
        migrations.AlterModelOptions(
            name="responsibility",
            options={
                "verbose_name": "Responsibility",
                "verbose_name_plural": "Responsibilities",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="staffmember",
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
            },
        ),
    ]
