# Generated by Django 5.0.6 on 2024-06-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_rename_expenseapproval_expensereview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="expensereview",
            options={
                "verbose_name": "Expense Review",
                "verbose_name_plural": "Expense Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="expensestatus",
            options={
                "verbose_name": "Expense Status",
                "verbose_name_plural": "Expense Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="itemizedexpense",
            options={
                "verbose_name": "Itemized Expense",
                "verbose_name_plural": "Itemized Expenses",
            },
        ),
    ]
