# Generated by Django 5.0.6 on 2024-06-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuetracking",
            options={
                "verbose_name": "Issue Tracking",
                "verbose_name_plural": "Issue Trackings",
            },
        ),
        migrations.AlterModelOptions(
            name="statustype",
            options={
                "verbose_name": "Status Type",
                "verbose_name_plural": "Status Types",
            },
        ),
        migrations.AlterModelOptions(
            name="websiterequest",
            options={
                "verbose_name": "Website Request",
                "verbose_name_plural": "Website Requests",
            },
        ),
    ]
